### ISSUE TITLE
[FR] Map Search

### ISSUE THREAD

**Issue by cadrianxyz** [onlinkers/event-discovery-prototype#34]
# Map Search

### Description of the feature
* The map search bar needs to be functional, allowing users to search for both places and events

### Purpose of the feature
* Allow users to use the **Discover** map to search for locations and events

### Tasks to complete
- [ ] Activate search for locations
- [ ] Implement autocomplete
- [ ] Connect to API (search by event name)
- [ ] Create smooth animations when a user to flies to a location
