### ISSUE TITLE
[FR] Map Navigation by Category

### ISSUE THREAD

**Issue by cadrianxyz** [onlinkers/event-discovery-prototype#35]
# Map Navigation by Category

### Description of the feature
* The map should have a list of the categories that the user can filter through (refer to figma designs)

### Purpose of the feature
* Allow users to filter events on the map by the category of events

### Tasks to complete
- [ ] Implement rolling category-picker
- [ ] Connect with API event query by category
- [ ] Title as well for mobile
