### ISSUE TITLE
[FR] New ‘view users’ Layer on Map

### ISSUE THREAD

**Issue by cadrianxyz** [onlinkers/event-discovery-prototype#76]
# New ‘view users’ Layer on Map

### Description of the feature
* Start implementation of rendering user locations

### Purpose of the feature
* Creating a layer allows 'toggling' the view on/off somehow. This makes it more dynamic & will make it scalable for any decisions in the future.

### Tasks to complete
- [ ] Create new map layer
- [ ] Load user data (decide how to limit)
- [ ] Implement locations based on designs
